version: "3"

services:
  postgres:
    image: postgres:10-alpine
    ports:
      - "5442:5432"
    environment:
      POSTGRES_DB: game-service-tests
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin123
  zookeeper2:
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9102:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100 #TODO change ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock